name: CI

# Run this workflow every time a commit is pushed to main or a pull request is opened against main
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
    build:
        name: Call Azure Pipeline
        runs-on: windows-2019
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/testloco/testDemo
            azure-pipeline-name: 'Richard12345.testwebsite'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_GITHUB_WEBSITE_TESTING }}
